name: Clean the logs of the run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_run: 
    workflows: [Check the pull requests]
    types:
      - completed

permissions:
  actions: write
