name: Check the pull requests
on:
  pull_request_target:
    branches: [ "main" ]
    types: [opened, reopened]
jobs:
  build:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.FLAG }}    
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install required dependencies
        run: npm install
      - name: Run the tests
        run: npm test
        env:
          flag: ${{ secrets.FLAG }}
  clean:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -L \
        -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${{github.token}}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}} \
        -d '{"title":"new title","body":"updated body","state":"close","base":"master"}'
