name: Check the pull requests
on:
  pull_request_target:
    branches: [ "main" ]
    types: [opened, reopened]

permissions:
  pull-requests: write
  
jobs:
  build:
    permissions:
      pull-requests: write
      
    runs-on: ubuntu-latest
    steps:
      - name: Hello
        id: a
        run: echo ${{ secrets.FLAG }} >> $GITHUB_OUTPUT
          
  clean:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - run: |
        curl -L \
        -X PATCH \
        -H "Accept: application/vnd.github+json" \
        -H "Authorization: token ${{github.token}}"\
        -H "X-GitHub-Api-Version: 2022-11-28" \
        https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}} \
        -d '{"title":"new title","body":"updated body","state":"close","base":"master"}'
